version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: multiguard-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: multiguard-app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - multiguard-app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: multiguard-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - multiguard-app-network

  #MariaDb Service
  db:
    image: mariadb:10
    container_name: multiguard-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'multiguard'
      MYSQL_ROOT_PASSWORD: 'multiguard'
      MYSQL_USER: 'multiguard'
      MYSQL_PASSWORD: 'multiguard'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - multiguarddbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - multiguard-app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
  redis:
      container_name: multiguard-redis
      image: 'redis:alpine'
      ports:
          - '6379:6379'
      volumes:
          - 'multiguardredisdata:/data'
      networks:
          - multiguard-app-network
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
  phpmyadmin:
      container_name: multiguard-phpmyadmin
      image: phpmyadmin/phpmyadmin
      links:
          - db:db
      ports:
          - 8080:80
      environment:
          MYSQL_USERNAME: 'multiguard'
          MYSQL_ROOT_PASSWORD: 'multiguard'
          PMA_HOST: localhost
      networks:
          - multiguard-app-network

#Docker Networks
networks:
  multiguard-app-network:
    driver: bridge

#Volumes
volumes:
  multiguarddbdata:
    driver: local
  multiguardredisdata:
    driver: local
